name: Attach Released Assets

on:
  release:
    types:
      - created

jobs:    
  zip-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: git submodule update --init --recursive

      - uses: papeloto/action-zip@v1
        with:
          files: corporate/ files/ noop/ parse-en-us/
          recursive: false
          dest: analyzers.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: analyzers.zip
          path: ${{ github.workspace }}/analyzers.zip
