name: Attach Released Assets

on:
  release:
    types:
      - created

jobs:    
  sub-modules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: git submodule update --init --recursive


  zip-files:
    needs: sub-modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: corporate/ files/ nlp-tutorials/ parse-en-us/
          recursive: false
          dest: analyzers.zip

      - uses: actions/upload-artifact@v1
        with:
          name: analyzers
          path: ${{ github.workspace }}/analyzers.zip
          
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: analyzers.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
